sudo: required
dist: trusty
os: linux
language: minimal
if: tag IS blank
addons:
  apt:
    packages:
    - build-essential
    - libtool
    - autotools-dev
    - automake
    - pkg-config
    - bsdmainutils
    - curl
    - git
    - python3
    - nsis
    - wine1.6
    - bc
    - software-properties-common
    
cache:
  directories:
  - depends/built
  - depends/sdk-sources
  - "$HOME/.ccache"
env:
  global:
  - MAKEJOBS=-j3
  - RUN_TESTS=false
  - CHECK_DOC=0
  - CHECK_LOGPRINT=0
  - BOOST_TEST_RANDOM=1$TRAVIS_BUILD_ID
  - CCACHE_SIZE=100M
  - CCACHE_TEMPDIR=/tmp/.ccache-temp
  - CCACHE_COMPRESS=1
  - BASE_OUTDIR=$TRAVIS_BUILD_DIR/out
  - SDK_URL=https://bitcoincore.org/depends-sources/sdks
  - WINEDEBUG=fixme-all
  matrix:
  - HOST=x86_64-pc-linux-gnu BITCOIN_CONFIG="--enable-glibc-back-compat LDFLAGS="-static-libstdc++"
  - HOST=x86_64-w64-mingw32 DPKG_ADD_ARCH="i386" BITCOIN_CONFIG="--enable-reduce-exports"
before_install:
#Upgraded GCC 5.3 and updated dpkg (dpkg on base Travis image is too old)
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo add-apt-repository ppa:adrozdoff/mingw -y
- sudo apt-get update
- sudo apt-get install -y gcc-5-mingw-w64 dpkg 
- sudo ln -s /usr/bin/x86_64-w64-mingw32-gcc-5 /usr/bin/x86_64-w64-mingw32-gcc
- sudo ln -s /usr/bin/x86_64-w64-mingw32-g++-5 /usr/bin/x86_64-w64-mingw32-g++
- wget http://de.archive.ubuntu.com/ubuntu/pool/universe/m/mingw-w64/mingw-w64-common_5.0.3-1_all.deb; sudo dpkg -i mingw-w64-common_5.0.3-1_all.deb
- export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" |
  sed "s|::|:|g")
before_script:
- if [ "$CHECK_DOC" = 1 ]; then contrib/devtools/check-doc.py; fi
- if [ "$CHECK_LOGPRINT" = 1 ]; then contrib/devtools/logprint-scanner.py; fi
- unset CC; unset CXX
- mkdir -p depends/SDKs depends/sdk-sources
- if [ -n "$OSX_SDK" -a ! -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then
  curl --location --fail $SDK_URL/MacOSX${OSX_SDK}.sdk.tar.gz -o depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz;
  fi
- if [ -n "$OSX_SDK" -a -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then
  tar -C depends/SDKs -xf depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz; fi
- make $MAKEJOBS -C depends HOST=$HOST
  $DEP_OPTS
script:
- export TRAVIS_COMMIT_LOG=`git log --format=fuller -1`
- if [ -n "$USE_SHELL" ]; then export CONFIG_SHELL="$USE_SHELL"; fi
- OUTDIR=$BASE_OUTDIR/$TRAVIS_PULL_REQUEST/$TRAVIS_JOB_NUMBER-$HOST
- BITCOIN_CONFIG_ALL="--disable-dependency-tracking --prefix=$TRAVIS_BUILD_DIR/depends/$HOST
  --bindir=$OUTDIR/bin --libdir=$OUTDIR/lib"
- depends/$HOST/native/bin/ccache --max-size=$CCACHE_SIZE
- test -n "$USE_SHELL" && eval '"$USE_SHELL" -c "./autogen.sh"' || ./autogen.sh
- "./configure --cache-file=config.cache $BITCOIN_CONFIG_ALL $BITCOIN_CONFIG || (
  cat config.log && false)"
- make distdir PACKAGE=bitcoin VERSION=$HOST
- cd bitcoin-$HOST
- "./configure --cache-file=../config.cache $BITCOIN_CONFIG_ALL $BITCOIN_CONFIG ||
  ( cat config.log && false)"
- make $MAKEJOBS $GOAL || ( echo "Build failure. Verbose build follows." && make $GOAL
  V=1 ; false )
- export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/depends/$HOST/lib
- if [ "$RUN_TESTS" = "true" ]; then travis_wait 30 make $MAKEJOBS check VERBOSE=1;
  fi
after_script:
- echo $TRAVIS_COMMIT_RANGE
- echo $TRAVIS_COMMIT_LOG
notifications:
  slack:
    secure: w22XjHoG/3xplxWzddS9Ma7i99Q/hq4FA3Q56xS+RtO2vlFgDT+eDzCppstdx96mn2/4e+/V1aiQ4E6GVEvJMeldqSUhPv9OBnKR0KJVAOwu4haNXt+0ZeQFt8lIndKB5cMVyOJkoq6peGoHNXslClM0lGuBn7g7VC2QPQYNWrJNrrGL7IiVb6fNOIKHWcC4URkzSvXAhO/WIqSSlmKxAAx0B2oEsM8LhdAbcjbp7Sm7zH87TIVGBZ7iTVuMc6B9+SfClbE8bBuRtvjTX57Q4UUZzn0zDtKdPdCte0oXdaQF4RdVim9mDodBGIpDo+avW4WL7EE+AK33fs94pwH5bu0LEandR/aeEvVpbSpQ2XsEKSe+6woizgl5i4GXFVZduJF62y/o1f+S/zC3qW9lIEEpiZc4PpX7pDy30X3p6S5nMrW7T/zNh+SjLhS1VP6XKdQtpD3WRCY4GKZYammZhk5RbOy3jTXAahIXuttWdhl/Q3Rb5VqfFJWlrG/qQXt73qOk2/DgJnABxXE6gnWO4MpHAq+kdomNR+nod4HeXI3DOk1wRuQRVoW1rSjiqQd6Db+TP56RKYgt4M4csOD0DG9G+W0AOtZkuKHTeoEtmQfkKFPZLYAQumv41cDN2UE9gKIECmvJSevj4sMCDTWtozKWqay/W4n2+cmhbzmGflY=
deploy:
  provider: releases
  skip_cleanup: true
  prerelease: true
  name: $TRAVIS_BRANCH 
  target_commitish: $TRAVIS_COMMIT
  overwrite: true  
  api_key:
    secure: B+KCKtU9vSQcNbZPgCewM43ABvQK/VcrYGasuzyF3hKxlSU68iR0Dw4Q+ScDCtXJw9eQ9C/yXBHwzaee21ucarQdQq6u8OhLYnmWmGy0xb0lEvDoVuBjpfTgMfvy3ZaxLrS7tYGFpDpmhD9802D3SChWy2Y0MUHsBbos8cfFLHzBkTBjlb07tTYaUZFbduIUKgvTQv5wczGDLpMqp/uK92RRErJHehvpJjRnzIGpRiPs9+1ziSk9rLuZweejnNUtQ6HpW6RQYDXQo8fHk1jd6Y9I5a+ajrQwNbsFUAwyhAnl1FS4avX49T5hzAt/EH9X0pT6pM97CW/D4K6nurH2tnUyHde79lzmaanyyhfEvt6Lycj3Angjk+od8rJCuDGsIeF4GsD+nH4G54WuqiaSRhGGG7t0qWqQN6HsGJtPPx7697sC3vAE5UpQ8v/YeDirAjCo0nvgvwZvdXPYkKYCRqPVmXbppffIiwDXgrnBz1sGjTGbC5YCIeIczAfnwfPspc5GYsQN7rZJEnSfGlcT9iscqi6rLlXDRgsl7Ny8eHa+d7dOY9QYC9xTZFILlfSGgFGjMej25uc9DKsiWs3j08vXTFKLoVzlOCbmcSS1teb8XnnYDB/c2kz1PZUTF9eLdbpDd1Of2iwth+fg8DoMEQU0KkuVLXimFzD+sa1yuHc=
  file: 
    - src/blocknode-cli
    - src/blocknoded
    - src/blocknode-tx
    - src/qt/blocknode-qt
  on:
    repo: CCob/blocknode
    all_branches: true
